export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
type AccountType="CUSTOMER"|"ADMIN"|"STAFF"|"SUPER_ADMIN"; type BookingMode="SEAT_BOOKING"|"FULL_VEHICLE_BOOKING"|"BOTH"; type VehicleStatus="active"|"maintenance"|"inactive"; type TripStatus="scheduled"|"in_progress"|"completed"|"cancelled"; type BookingStatus="PENDING"|"CONFIRMED"|"CANCELLED"|"COMPLETED"|"REFUND_PENDING"|"REFUNDED"; type SeatLockStatus="LOCKED"|"RELEASED"|"CONSUMED"; type PaymentStatus="PENDING"|"PROCESSING"|"SUCCESS"|"FAILED"|"CANCELLED"|"REFUND_PENDING"|"REFUNDED"; type NotificationChannel="IN_APP"|"EMAIL"|"SMS"|"WHATSAPP"; type NotificationStatus="PENDING"|"PROCESSING"|"SENT"|"FAILED"|"CANCELLED"; type AnalyticsEventType="search_performed"|"route_viewed"|"trip_viewed"|"vehicle_viewed"|"seat_selected"|"booking_started"|"booking_abandoned"|"booking_completed"|"booking_cancelled"|"recommendation_viewed"|"recommendation_clicked";
type Table<Row,Insert=Partial<Row>,Update=Partial<Insert>>={Row:Row;Insert:Insert;Update:Update;Relationships:[]};
export interface Database { public:{ Tables:{
profiles:Table<{id:string;account_type:AccountType;full_name:string|null;phone:string|null;created_at:string;updated_at:string},{id:string;account_type?:AccountType;full_name?:string|null;phone?:string|null;created_at?:string;updated_at?:string}>;
organizations:Table<{id:string;name:string;created_at:string;updated_at:string},{id?:string;name:string;created_at?:string;updated_at?:string}>;
organization_memberships:Table<{id:string;organization_id:string;user_id:string;role:"OWNER"|"ADMIN"|"STAFF";created_at:string},{id?:string;organization_id:string;user_id:string;role:"OWNER"|"ADMIN"|"STAFF";created_at?:string}>;
partner_terms_acceptances:Table<{id:string;user_id:string;organization_name:string;terms_version:string;accepted_at:string;created_at:string},{id?:string;user_id:string;organization_name:string;terms_version:string;accepted_at?:string;created_at?:string}>;
vehicle_types:Table<{id:string;name:string;booking_mode:BookingMode;created_at:string},{id?:string;name:string;booking_mode:BookingMode;created_at?:string}>;
vehicles:Table<{id:string;organization_id:string;vehicle_type_id:string;registration_number:string;label:string;seat_capacity:number|null;status:VehicleStatus;created_at:string;updated_at:string},{id?:string;organization_id:string;vehicle_type_id:string;registration_number:string;label:string;seat_capacity?:number|null;status?:VehicleStatus;created_at?:string;updated_at?:string}>;
vehicle_seats:Table<{id:string;vehicle_id:string;seat_number:string;seat_type:string|null;created_at:string},{id?:string;vehicle_id:string;seat_number:string;seat_type?:string|null;created_at?:string}>;
locations:Table<{id:string;name:string;city:string|null;state:string|null;pincode:string|null;latitude:number|null;longitude:number|null;created_at:string},{id?:string;name:string;city?:string|null;state?:string|null;pincode?:string|null;latitude?:number|null;longitude?:number|null;created_at?:string}>;
geo_districts:Table<{state_code:'CG'|'OD';name:string},{state_code:'CG'|'OD';name:string}>;
geo_post_offices:Table<{state_code:'CG'|'OD';district:string|null;postal_division:string;office_name:string;pincode:string;source:'INDIA_POST'},{state_code:'CG'|'OD';district?:string|null;postal_division:string;office_name:string;pincode:string;source:'INDIA_POST'}>;
routes:Table<{id:string;organization_id:string;origin_location_id:string;destination_location_id:string;name:string;distance_km:number|null;created_at:string;updated_at:string},{id?:string;organization_id:string;origin_location_id:string;destination_location_id:string;name:string;distance_km?:number|null;created_at?:string;updated_at?:string}>;
route_stops:Table<{id:string;route_id:string;location_id:string;stop_order:number;is_pickup:boolean;is_drop:boolean;created_at:string},{id?:string;route_id:string;location_id:string;stop_order:number;is_pickup?:boolean;is_drop?:boolean;created_at?:string}>;
trips:Table<{id:string;route_id:string;vehicle_id:string;departure_at:string;arrival_at:string|null;status:TripStatus;base_price:number;created_at:string;updated_at:string},{id?:string;route_id:string;vehicle_id:string;departure_at:string;arrival_at?:string|null;status?:TripStatus;base_price:number;created_at?:string;updated_at?:string}>;
bookings:Table<{id:string;user_id:string;trip_id:string;booking_mode:BookingMode;status:BookingStatus;passenger_count:number;amount:number;created_at:string;updated_at:string}>;
booking_passengers:Table<{id:string;booking_id:string;full_name:string;phone:string;created_at:string}>;
seat_locks:Table<{id:string;trip_id:string;seat_id:string;user_id:string;status:SeatLockStatus;expires_at:string;created_at:string;updated_at:string}>;
booking_seats:Table<{booking_id:string;trip_id:string;seat_id:string;created_at:string;released_at:string|null}>;
booking_cancellations:Table<{id:string;booking_id:string;user_id:string;reason:string|null;refund_amount:number;created_at:string}>;
payments:Table<{id:string;booking_id:string;user_id:string;provider:string;provider_order_id:string|null;provider_payment_id:string|null;provider_refund_id:string|null;refund_amount:number|null;refund_initiated_at:string|null;status:PaymentStatus;amount:number;currency:string;failure_code:string|null;failure_message:string|null;created_at:string;updated_at:string;paid_at:string|null}>;
payment_events:Table<{id:number;payment_id:string|null;provider:string;provider_event_id:string;event_type:string;payload:Json;processed_at:string|null;created_at:string}>;
notifications:Table<{id:string;user_id:string;booking_id:string|null;channel:NotificationChannel;event_type:string;title:string;message:string;status:NotificationStatus;provider:string|null;provider_message_id:string|null;failure_message:string|null;read_at:string|null;sent_at:string|null;created_at:string;updated_at:string}>;
analytics_events:Table<{id:string;event_type:AnalyticsEventType;user_id:string|null;session_id:string|null;properties:Json;created_at:string},{id?:string;event_type:AnalyticsEventType;user_id?:string|null;session_id?:string|null;properties?:Json;created_at?:string}>;
}; Views:Record<string,never>; Functions:{ partner_complete_booking:{Args:{p_booking_id:string};Returns:BookingStatus}; partner_decide_booking:{Args:{p_booking_id:string;p_decision:string;p_reason?:string|null};Returns:BookingStatus}; acquire_seat_locks:{Args:{p_trip_id:string;p_seat_ids:string[];p_ttl_seconds?:number};Returns:Database['public']['Tables']['seat_locks']['Row'][]}; release_seat_locks:{Args:{p_trip_id:string;p_seat_ids?:string[]|null};Returns:number}; trip_seat_availability:{Args:{p_trip_id:string};Returns:{seat_id:string;availability:string}[]}; is_super_admin:{Args:Record<string,never>;Returns:boolean}; current_organization_ids:{Args:Record<string,never>;Returns:string[]}; activate_partner:{Args:{p_organization_name:string;p_terms_version:string};Returns:string}; supervision_overview:{Args:Record<string,never>;Returns:{organization_id:string;organization_name:string;vehicle_id:string;vehicle_label:string;registration_number:string;vehicle_status:VehicleStatus;trip_id:string|null;trip_status:TripStatus|null;departure_at:string|null;arrival_at:string|null;booking_id:string|null;customer_id:string|null;booking_status:BookingStatus|null;booking_amount:number|null;base_price:number|null;discount_amount:number|null;origin_name:string|null;destination_name:string|null}[]}; create_seat_booking:{Args:{p_trip_id:string;p_seat_ids:string[];p_passengers:Json};Returns:string}; create_full_vehicle_booking:{Args:{p_trip_id:string;p_passengers:Json};Returns:string}; start_payment:{Args:{p_booking_id:string;p_provider?:string};Returns:string}; cancel_booking:{Args:{p_booking_id:string;p_reason?:string};Returns:BookingStatus}; mark_notification_read:{Args:{p_notification_id:string};Returns:undefined}; analytics_summary:{Args:{p_days?:number};Returns:{event_type:AnalyticsEventType;event_count:number;unique_users:number}[]} }; Enums:{account_type:AccountType;booking_mode:BookingMode;vehicle_status:VehicleStatus;trip_status:TripStatus;booking_status:BookingStatus;seat_lock_status:SeatLockStatus;payment_status:PaymentStatus;notification_channel:NotificationChannel;notification_status:NotificationStatus;analytics_event_type:AnalyticsEventType}; CompositeTypes:Record<string,never> } }
