export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];
type AccountType="CUSTOMER"|"ADMIN"|"STAFF"; type BookingMode="SEAT_BOOKING"|"FULL_VEHICLE_BOOKING"|"BOTH"; type VehicleStatus="active"|"maintenance"|"inactive"; type TripStatus="scheduled"|"in_progress"|"completed"|"cancelled"; type BookingStatus="PENDING"|"CONFIRMED"|"CANCELLED"|"COMPLETED"|"REFUND_PENDING"|"REFUNDED"; type SeatLockStatus="LOCKED"|"RELEASED"|"CONSUMED"; type PaymentStatus="PENDING"|"PROCESSING"|"SUCCESS"|"FAILED"|"CANCELLED"|"REFUND_PENDING"|"REFUNDED";
type Table<Row,Insert=Partial<Row>,Update=Partial<Insert>>={Row:Row;Insert:Insert;Update:Update;Relationships:[]};
export interface Database { public:{ Tables:{
profiles:Table<{id:string;account_type:AccountType;full_name:string|null;phone:string|null;created_at:string;updated_at:string},{id:string;account_type?:AccountType;full_name?:string|null;phone?:string|null;created_at?:string;updated_at?:string}>;
organizations:Table<{id:string;name:string;created_at:string;updated_at:string},{id?:string;name:string;created_at?:string;updated_at?:string}>;
vehicle_types:Table<{id:string;name:string;booking_mode:BookingMode;created_at:string},{id?:string;name:string;booking_mode:BookingMode;created_at?:string}>;
vehicles:Table<{id:string;organization_id:string;vehicle_type_id:string;registration_number:string;label:string;seat_capacity:number|null;status:VehicleStatus;created_at:string;updated_at:string},{id?:string;organization_id:string;vehicle_type_id:string;registration_number:string;label:string;seat_capacity?:number|null;status?:VehicleStatus;created_at?:string;updated_at?:string}>;
vehicle_seats:Table<{id:string;vehicle_id:string;seat_number:string;seat_type:string|null;created_at:string},{id?:string;vehicle_id:string;seat_number:string;seat_type?:string|null;created_at?:string}>;
locations:Table<{id:string;name:string;city:string|null;state:string|null;latitude:number|null;longitude:number|null;created_at:string},{id?:string;name:string;city?:string|null;state?:string|null;latitude?:number|null;longitude?:number|null;created_at?:string}>;
routes:Table<{id:string;organization_id:string;origin_location_id:string;destination_location_id:string;name:string;distance_km:number|null;created_at:string;updated_at:string},{id?:string;organization_id:string;origin_location_id:string;destination_location_id:string;name:string;distance_km?:number|null;created_at?:string;updated_at?:string}>;
route_stops:Table<{id:string;route_id:string;location_id:string;stop_order:number;is_pickup:boolean;is_drop:boolean;created_at:string},{id?:string;route_id:string;location_id:string;stop_order:number;is_pickup?:boolean;is_drop?:boolean;created_at?:string}>;
trips:Table<{id:string;route_id:string;vehicle_id:string;departure_at:string;arrival_at:string|null;status:TripStatus;base_price:number;created_at:string;updated_at:string},{id?:string;route_id:string;vehicle_id:string;departure_at:string;arrival_at?:string|null;status?:TripStatus;base_price:number;created_at?:string;updated_at?:string}>;
bookings:Table<{id:string;user_id:string;trip_id:string;booking_mode:BookingMode;status:BookingStatus;passenger_count:number;amount:number;created_at:string;updated_at:string}>;
booking_passengers:Table<{id:string;booking_id:string;full_name:string;phone:string;created_at:string}>;
seat_locks:Table<{id:string;trip_id:string;seat_id:string;user_id:string;status:SeatLockStatus;expires_at:string;created_at:string;updated_at:string}>;
booking_seats:Table<{booking_id:string;trip_id:string;seat_id:string;created_at:string}>;
payments:Table<{id:string;booking_id:string;user_id:string;provider:string;provider_order_id:string|null;provider_payment_id:string|null;status:PaymentStatus;amount:number;currency:string;failure_code:string|null;failure_message:string|null;created_at:string;updated_at:string;paid_at:string|null}>;
payment_events:Table<{id:number;payment_id:string|null;provider:string;provider_event_id:string;event_type:string;payload:Json;processed_at:string|null;created_at:string}>;
}; Views:Record<string,never>; Functions:{ acquire_seat_locks:{Args:{p_trip_id:string;p_seat_ids:string[];p_ttl_seconds?:number};Returns:Database['public']['Tables']['seat_locks']['Row'][]}; create_seat_booking:{Args:{p_trip_id:string;p_seat_ids:string[];p_passengers:Json};Returns:string}; create_full_vehicle_booking:{Args:{p_trip_id:string;p_passengers:Json};Returns:string}; start_payment:{Args:{p_booking_id:string;p_provider?:string};Returns:string} }; Enums:{account_type:AccountType;booking_mode:BookingMode;vehicle_status:VehicleStatus;trip_status:TripStatus;booking_status:BookingStatus;seat_lock_status:SeatLockStatus;payment_status:PaymentStatus}; CompositeTypes:Record<string,never> } }