import type { Metadata } from "next";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { createClient } from "@/lib/supabase/server";

export const metadata: Metadata = { title: "Search Trips" };
type Props={searchParams:Promise<{from?:string;to?:string;date?:string;passengers?:string}>};
type Location={id:string;name:string;city:string|null};
function normalize(value:string){return value.trim().toLocaleLowerCase().replace(/\s+/g," ");}
function matchLocation(locations:Location[],query:string){const q=normalize(query);if(!q)return {location:undefined,ambiguous:false};const exact=locations.filter(l=>normalize(l.name)===q||normalize(l.city??"")===q||normalize(`${l.name} ${l.city??""}`)===q);if(exact.length===1)return {location:exact[0],ambiguous:false};if(exact.length>1)return {location:undefined,ambiguous:true};const fuzzy=locations.filter(l=>normalize(`${l.name} ${l.city??""}`).includes(q));return fuzzy.length===1?{location:fuzzy[0],ambiguous:false}:{location:undefined,ambiguous:fuzzy.length>1};}

export default async function SearchPage({searchParams}:Props){
 const params=await searchParams;const from=params.from?.trim()??"";const to=params.to?.trim()??"";const date=params.date??"";const rawPassengers=Number(params.passengers);const passengers=Number.isInteger(rawPassengers)?Math.min(50,Math.max(1,rawPassengers)):1;const supabase=await createClient();
 const {data:locations}=await supabase.from("locations").select("id,name,city").order("name");const all=(locations??[]) as Location[];const originMatch=matchLocation(all,from);const destinationMatch=matchLocation(all,to);const origin=originMatch.location;const destination=destinationMatch.location;
 let results:Array<{id:string;route_id:string;vehicle_id:string;departure_at:string;arrival_at:string|null;status:string;base_price:number}>=[];if(origin&&destination&&origin.id!==destination.id){const{data:routes}=await supabase.from("routes").select("id").eq("origin_location_id",origin.id).eq("destination_location_id",destination.id);const routeIds=(routes??[]).map(r=>r.id);if(routeIds.length){let query=supabase.from("trips").select("id,route_id,vehicle_id,departure_at,arrival_at,status,base_price").in("route_id",routeIds).eq("status","scheduled").gte("departure_at",new Date().toISOString()).order("departure_at");if(date&&/^\d{4}-\d{2}-\d{2}$/.test(date)){const start=`${date}T00:00:00.000Z`;const next=new Date(start);next.setUTCDate(next.getUTCDate()+1);query=query.gte("departure_at",start).lt("departure_at",next.toISOString());}const{data}=await query;results=data??[];}}
 const vehicleIds=[...new Set(results.map(r=>r.vehicle_id))];const{data:vehicles}=vehicleIds.length?await supabase.from("vehicles").select("id,label,registration_number,seat_capacity,vehicle_type_id").in("id",vehicleIds):{data:[]};const vehicleMap=new Map((vehicles??[]).map(v=>[v.id,v]));const unmatched=from&&to&&(!origin||!destination);const ambiguous=originMatch.ambiguous||destinationMatch.ambiguous;
 return <div className="mx-auto max-w-6xl space-y-8 px-4 py-10 sm:py-14"><div><h1 className="text-3xl font-semibold tracking-tight">Search trips</h1><p className="mt-2 text-muted-foreground">Search scheduled transport using live route and trip data.</p></div><form className="grid gap-3 rounded-2xl border bg-card p-5 shadow-lg shadow-black/5 md:grid-cols-[1fr_1fr_180px_120px_auto]"><Input name="from" defaultValue={from} placeholder="From" required/><Input name="to" defaultValue={to} placeholder="To" required/><Input name="date" type="date" defaultValue={date}/><Input name="passengers" type="number" min={1} max={50} defaultValue={passengers}/><Button type="submit">Search</Button></form>{unmatched?<div className="rounded-lg border border-dashed p-6 text-sm text-muted-foreground">{ambiguous?"That location matches multiple places. Enter the full location or city name so we do not guess your route.":"We could not match one of those locations. Try a city or location available in the network."}</div>:null}{origin&&destination&&origin.id===destination.id?<div className="rounded-lg border border-dashed p-6 text-sm text-muted-foreground">Origin and destination must be different.</div>:null}{origin&&destination&&origin.id!==destination.id&&!results.length?<div className="rounded-xl border border-dashed p-10 text-center"><p className="font-medium">No trips found</p><p className="mt-1 text-sm text-muted-foreground">Try another date or route. Availability is never fabricated.</p></div>:null}<div className="grid gap-4">{results.map(trip=>{const vehicle=vehicleMap.get(trip.vehicle_id);return <article key={trip.id} className="rounded-2xl border bg-card p-5 shadow-sm transition-all hover:-translate-y-0.5 hover:shadow-md"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-lg font-semibold">{origin?.name} → {destination?.name}</p><p className="mt-1 text-sm text-muted-foreground">{new Date(trip.departure_at).toLocaleString()}{trip.arrival_at?` — ${new Date(trip.arrival_at).toLocaleString()}`:""}</p><p className="mt-2 text-sm">{vehicle?`${vehicle.label} · ${vehicle.registration_number}`:"Assigned vehicle"}{vehicle?.seat_capacity?` · ${vehicle.seat_capacity} seats`:""} · From ₹{Number(trip.base_price).toFixed(2)}</p></div><Button asChild><Link href={`/booking?trip=${trip.id}&passengers=${passengers}`}>View trip</Link></Button></div></article>})}</div></div>;
}
